asset validation init
GridPlus/phonon-network pull request #49
Opened 2022-10-05 15:05 UTC by zerodouglas

2022-10-07 15:14 UTC, maevyn11 requested changes
Left some general commentary.

2022-10-07 15:14 UTC, maevyn11 commented on asset-validation.md
> +
and this document describes how that current implementation is going to change?

2022-10-07 15:14 UTC, maevyn11 commented on asset-validation.md
> +	Invalid bool
I'd suggest `Valid` instead of `Invalid` for the status, otherwise the happy path is a double negative `Invalid: false` whereas I think you'd expect `Valid: true` in that case.

2022-10-07 15:14 UTC, maevyn11 commented on asset-validation.md
> +	Status string
This should probably be an error type instead so that asset validation implementation can pass back their own custom errors, and nil can represent no error.

2022-10-07 15:14 UTC, maevyn11 commented on asset-validation.md
> +	Invalid bool
Also KeyIndex should probably just be `index` since the assets we're validating may not be resident in a Phonon Card KeyIndex at the point of validation. When they are pending approval they will just be a part of a proposal with it's own internal indices. I would suggest we use an internal indexing scheme or just return the whole phonon definition with the results, with "descriptorValidated" or similar set to `true`

2022-10-07 15:14 UTC, maevyn11 commented on asset-validation.md
> +
Needs an interface definition with a method signature for say ValidatePhononDescriptor(). What is the input data? Entire phonon? Narrowest set of fields that is required? The output seems to be defined below with assetValidationStatus

2022-10-27 18:43 UTC, maevyn11 requested changes
One comment on the ETH validation example, otherwise I think this is good to go. Still not sure where to store it though so need to just figure that out before merging. Maybe a dedicated Spec section for a historical record of work in progress?

2022-10-27 19:41 UTC, zerodouglas commented on asset-validation.md
> +3. Derive the wallet address from the public key and check if the address exists and its on-chain balance.
Perhaps we should have a dedicated spec section, it would allow us to add other examples as well.

2022-10-27 19:45 UTC, zerodouglas commented on asset-validation.md
> +3. Derive the wallet address from the public key and check if the address exists and its on-chain balance.
Changes at https://github.com/GridPlus/phonon-network/pull/49/commits/70d8edb1ba086bda97d3771d74f6bcf888d09f32

2022-11-02 22:08 UTC, maevyn11 commented
Closing in favor of storing in phonon-roadmap

2022-11-02 22:08 UTC, closed without merging